# You need to change  vm.max_map_count to 262144 or more before start elasticsearch.
# Ref. https://www.elastic.co/guide/en/elasticsearch/reference/8.15/_maximum_map_count_check.html
# $ echo | sudo tee -a /etc/sysctl.conf
# $ echo 'vm.max_map_count=262144' | sudo tee -a /etc/sysctl.conf
# $ reboot
name: Kibana
services:
  es:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - ELASTIC_PASSWORD=elastic
      - discovery.type=single-node
      - node.name=es
      - xpack.security.enabled=false
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    labels:
      icon: https://icon.casaos.io/main/all/kibana.png
    ports:
      - target: 9200
        published: "9200"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/kibana/esdata
        target: /usr/share/elasticsearch/data
    devices: []
    cap_add: []
    networks:
      - es
    privileged: false
    container_name: ""
    hostname: ""
  kibana:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_PASSWORD=elastic
      - ELASTICSEARCH_USERNAME=kibana_system
      - SERVERNAME=kibana
      - SERVER_PUBLICBASEURL=http://your-hostname:5601/
      - xpack.security.enabled=false
    image: docker.elastic.co/kibana/kibana:8.15.1
    labels:
      icon: https://icon.casaos.io/main/all/kibana.png
    ports:
      - target: 5601
        published: "5601"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/kibana/kibanadata
        target: /usr/share/kibana/data
    devices: []
    cap_add: []
    networks:
      - es
    privileged: false
    container_name: ""
    hostname: ""
networks:
  es:
    name: es
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/kibana.png
  index: /
  is_uncontrolled: false
  port_map: "5601"
  scheme: http
  store_app_id: Kibana
  title:
    custom: Kibana
